language: php

php:
  - '7.1'

services:
  - mysql

addons:
  - mariadb: '10.2'

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS phparcade;'
  - mysql -u root phparcade < installation/create_database.sql

install:
  - composer install --no-dev

script: phpunit --configuration phpunit.xml tests

