language: php

php:
  - '7.1'

services:
  - mysql

addons:
  - mariadb: '10.2'

before_install:
  - git clone https://github.com/Sageth/phparcade.git
  - composer install --no-dev
  - mysql -u root --password="" < installation/create_database.sql

script: phpunit tests

